// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfXZQvrRUyheyVCY6wwCMjx4LRyjBy6n0',
    appId: '1:384518109352:web:3ae3ecf57033fd343c6a9d',
    messagingSenderId: '384518109352',
    projectId: 'movies-app-rewan',
    authDomain: 'movies-app-rewan.firebaseapp.com',
    storageBucket: 'movies-app-rewan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp6tJbWTlatyzpqHg3pmSWFrF2ANsS-EU',
    appId: '1:384518109352:android:9a7e1067888ddca33c6a9d',
    messagingSenderId: '384518109352',
    projectId: 'movies-app-rewan',
    storageBucket: 'movies-app-rewan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe7_IfvRcMGyQTd-DcjSX8aqX0XwDFl6s',
    appId: '1:384518109352:ios:ee3815d7c0c7381e3c6a9d',
    messagingSenderId: '384518109352',
    projectId: 'movies-app-rewan',
    storageBucket: 'movies-app-rewan.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe7_IfvRcMGyQTd-DcjSX8aqX0XwDFl6s',
    appId: '1:384518109352:ios:ee3815d7c0c7381e3c6a9d',
    messagingSenderId: '384518109352',
    projectId: 'movies-app-rewan',
    storageBucket: 'movies-app-rewan.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfXZQvrRUyheyVCY6wwCMjx4LRyjBy6n0',
    appId: '1:384518109352:web:8fc24852b378e7df3c6a9d',
    messagingSenderId: '384518109352',
    projectId: 'movies-app-rewan',
    authDomain: 'movies-app-rewan.firebaseapp.com',
    storageBucket: 'movies-app-rewan.firebasestorage.app',
  );
}
